### ISSUE TITLE
Return back value of HOME variable

### ISSUE THREAD

**Issue by lucomsky** [tillsteinbach/gitolite-ldap-config#1]
It'll be good to have HOME variable back after changes in gitolite_ssh_wrapper_script.sh. See my proposed versions of changes in attach.

[home_dir_back.txt](https://github.com/tillsteinbach/gitolite-ldap-config/files/674123/home_dir_back.txt)

**Comment by tillsteinbach** [comment]
Thank you for your proposal. Can I ask you to provide a pull request with your changes?

**Comment by tillsteinbach** [comment]
merged! Thank you for your contribution!
