### ISSUE TITLE
Shell commands needs fix

### ISSUE THREAD

**Issue by lucomsky** [tillsteinbach/gitolite-ldap-config#2]
$SSH_ORIGINAL_COMMAND needs parentheses in gitolite_ssh_wrapper_script.sh!
See attach.

[shell_commands_fix.txt](https://github.com/tillsteinbach/gitolite-ldap-config/files/674159/shell_commands_fix.txt)

**Comment by tillsteinbach** [comment]
Thank you for your error report. Can I ask you to provide a pull request with your changes?

**Comment by tillsteinbach** [comment]
merged! Thank you for your contribution!
